-- 示例数据库文件
create table bossfi_demo
(
    id          bigint not null GENERATED BY DEFAULT AS IDENTITY
        primary key,
    address     varchar,
    logs        jsonb,
    deleted     boolean,
    create_time timestamp(6),
    modify_time timestamp(6)
);
comment on table bossfi_demo is 'Demo列表';
comment on column bossfi_demo.id is 'id';
comment on column bossfi_demo.address is 'address';
comment on column bossfi_demo.logs is 'logs';
comment on column bossfi_demo.deleted is '是否删除(逻辑,true-删除，false-未删除)';
comment on column bossfi_demo.create_time is '创建时间';
comment on column bossfi_demo.modify_time is '更新时间';

alter table bossfi_demo owner to bossfi;

-- 测试数据
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x123', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x234', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x345', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x456', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x567', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x678', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x789', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x890', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x901', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x910', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x911', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x912', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x913', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x914', '{}', false, now(), now());
insert into bossfi_demo (address, logs, deleted, create_time, modify_time) values ('0x915', '{}', false, now(), now());
