-- CREATE USER bossfi WITH PASSWORD 'bossfi';

create table bii_user_balance
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address     VARCHAR(42),
    balance     NUMERIC(78, 0) NOT NULL,
    points numeric(78) default 0 not null,
    deleted     BOOLEAN,
    create_time TIMESTAMP(6),
    modify_time TIMESTAMP(6)
);
comment on table bii_user_balance is '用户余额表';
comment on column bii_user_balance.id is '主键ID';
comment on column bii_user_balance.address is '用户地址';
comment on column bii_user_balance.balance is '用户余额';
comment on column bii_user_balance.points is '积分';
comment on column bii_user_balance.deleted is '逻辑删除字段 (true:删除 false:未删除)';
comment on column bii_user_balance.create_time is '创建时间';
comment on column bii_user_balance.modify_time is '更新时间';
alter table bii_user_balance owner to bossfi;
create unique index idx_bii_user_balance_address on bii_user_balance (address);

create table bii_user_balance_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address        VARCHAR(42),
    log_type       INTEGER        NOT NULL,
    before_balance NUMERIC(78, 0) NOT NULL,
    change_balance NUMERIC(78, 0) NOT NULL,
    after_balance  NUMERIC(78, 0) NOT NULL,
    tx_hash        VARCHAR(66),
    deleted        BOOLEAN,
    create_time    TIMESTAMP(6),
    modify_time    TIMESTAMP(6)
);

comment on table bii_user_balance_log is '用户余额日志表';
comment on column bii_user_balance_log.id is '主键ID';
comment on column bii_user_balance_log.address is '用户地址';
comment on column bii_user_balance_log.log_type is '日志类型 0:系统校准,1:收入;2:支出;3:区块重组';
comment on column bii_user_balance_log.before_balance is '操作前余额';
comment on column bii_user_balance_log.change_balance is '变更余额';
comment on column bii_user_balance_log.after_balance is '操作后余额';
comment on column bii_user_balance_log.tx_hash is '交易hash';
comment on column bii_user_balance_log.deleted is '逻辑删除字段 (true:删除 false:未删除)';
comment on column bii_user_balance_log.create_time is '创建时间';
comment on column bii_user_balance_log.modify_time is '更新时间';
alter table bii_user_balance_log owner to bossfi;
create index idx_bii_user_balance_log_address on bii_user_balance_log (address);

CREATE TABLE bii_token_event
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_number BIGINT      NOT NULL,
    block_hash   VARCHAR(66) NOT NULL,
    tx_hash      VARCHAR(66) NOT NULL,
    log_index    INTEGER     NOT NULL,
    event_type   INTEGER     NOT NULL,
    from_address VARCHAR(42),
    to_address   VARCHAR(42),
    amount       NUMERIC(78, 0),
    confirmed    BOOLEAN DEFAULT FALSE,
    deleted        BOOLEAN,
    create_time  TIMESTAMP(6),
    modify_time  TIMESTAMP(6)
);
comment on table bii_token_event is 'ERC20代币事件表';
comment on column bii_token_event.id is '主键ID';
comment on column bii_token_event.block_number is '区块高度';
comment on column bii_token_event.block_hash is '区块hash';
comment on column bii_token_event.tx_hash is '交易hash';
comment on column bii_token_event.log_index is '日志索引';
comment on column bii_token_event.event_type is '事件类型 1:Transfer,2:Mint,3:Burn';
comment on column bii_token_event.from_address is '转出地址';
comment on column bii_token_event.to_address is '转入地址';
comment on column bii_token_event.amount is '转账金额';
comment on column bii_token_event.confirmed is '是否确认';
comment on column bii_token_event.deleted is '逻辑删除字段 (true:删除 false:未删除)';
comment on column bii_token_event.create_time is '创建时间';
comment on column bii_token_event.modify_time is '更新时间';
alter table bii_token_event owner to bossfi;
create index idx_bii_token_event_block_number on bii_token_event (block_number);
create unique index idx_bii_token_event_tx_hash_log_index on bii_token_event (tx_hash, log_index);

create table bii_user_points_log
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address      VARCHAR(42),
    log_type     INTEGER        NOT NULL,
    before_points NUMERIC(78, 0) NOT NULL,
    change_points NUMERIC(78, 0) NOT NULL,
    after_points  NUMERIC(78, 0) NOT NULL,
    tx_hash      VARCHAR(66),
    deleted      BOOLEAN,
    create_time  TIMESTAMP(6),
    modify_time  TIMESTAMP(6)
);

comment on table bii_user_points_log is '用户积分日志表';
comment on column bii_user_points_log.id is '主键ID';
comment on column bii_user_points_log.address is '用户地址';
comment on column bii_user_points_log.log_type is '日志类型 0:系统,1:收入;2:支出';
comment on column bii_user_points_log.before_points is '操作前积分';
comment on column bii_user_points_log.change_points is '变更积分';
comment on column bii_user_points_log.after_points is '操作后积分';
comment on column bii_user_points_log.tx_hash is '交易hash';
comment on column bii_user_points_log.deleted is '逻辑删除字段 (true:删除 false:未删除)';
comment on column bii_user_points_log.create_time is '创建时间';
comment on column bii_user_points_log.modify_time is '更新时间';
alter table bii_user_points_log
    owner to bossfi;
create index idx_bii_user_points_log_address on bii_user_points_log (address);